
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Topbar from '../../components/Topbar'
import Bottombar from '../../components/Bottombar'
import Leftsidebar from '../../components/Leftsidebar'
import Rightsidebar from '../../components/Rightsidebar'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Connectify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">

      <body className={`${inter.className}`}>
        <Topbar/>

        <main className='flex flex-row'>
          <Leftsidebar/>
          <section className='main-container'>
            <div className='w-full max-w-4xl'>
                {children}
            </div>
          </section>
          <Rightsidebar/>
        </main>

    <div className='block md:hidden'>
        <Bottombar/>
    </div>
        </body>
    </html>
    </ClerkProvider>
  )
}
